name: Build Task
on: [push]
jobs:

  build:
    name: Test
    runs-on: ${{ matrix.vm-os }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
#        vm-os: [ubuntu-latest]
#        go-version: [1.13.5]
         vm-os: [ubuntu-latest, macOS-latest, windows-latest]
         go-version: [1.11.13, 1.12.13, 1.13.5]

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      shell: bash
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Setup Environment
      shell: bash
      run: |
        ./setup.sh

    - name: Build
      shell: bash
      run: |
        make ci

    - name: Run
      shell: bash
      run: |
        make run
